// <auto-generated />
using System;
using Demo.Services.ShoppingCartAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Services.ShoppingCartAPI.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20230802024858_SeedShoppingCartTable")]
    partial class SeedShoppingCartTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("890a05e1-e229-4126-989d-b76bd9287dbe"),
                            UserId = new Guid("d0faab23-c93c-42dd-b455-af2c6187f3f4")
                        },
                        new
                        {
                            Id = new Guid("55bd8681-b566-4286-80a5-7763fa964c88"),
                            UserId = new Guid("66b041a3-4ab5-4733-93d9-2c6f343ff490")
                        });
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCartDetail", b =>
                {
                    b.Property<Guid>("ShoppingCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingCartDetailId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartDetail");
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCartDetail", b =>
                {
                    b.HasOne("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartDetail")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
