// <auto-generated />
using System;
using Demo.Services.ShoppingCartAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Services.ShoppingCartAPI.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20230801050422_SeedShoppingCartDb")]
    partial class SeedShoppingCartDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCartDetail", b =>
                {
                    b.Property<Guid>("ShoppingCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingCartDetailId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartDetail");
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCartDetail", b =>
                {
                    b.HasOne("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartDetail")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Demo.Services.ShoppingCartAPI.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
