// <auto-generated />
using System;
using Demo.Services.CompanyAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Services.CompanyAPI.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20230712050744_ChangeTableName")]
    partial class ChangeTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Services.CompanyAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("164a84b0-1714-4954-b6f5-482c77f8a1d9"),
                            City = "San Diego",
                            CompanyName = "Nike",
                            Description = "Just Do It!",
                            NumberOfEmployees = 5000,
                            PhoneNumber = "777-448-8511",
                            State = "CA",
                            StreetAddress = "5684 Middleton Ave",
                            WebsiteUrl = "www.nike.com",
                            ZipCode = "55255"
                        },
                        new
                        {
                            Id = new Guid("5fca7e70-a8d3-4583-94a5-3ed2e0a06029"),
                            City = "New York",
                            CompanyName = "Adidas",
                            Description = "The Brand With 3 Stripes!",
                            NumberOfEmployees = 4000,
                            PhoneNumber = "548-358-7711",
                            State = "NY",
                            StreetAddress = "6481 Southern Ave",
                            WebsiteUrl = "www.adidas.com",
                            ZipCode = "87246"
                        },
                        new
                        {
                            Id = new Guid("20859284-7130-4caf-bb96-e8d586555ff5"),
                            City = "Phoenix",
                            CompanyName = "ASOS",
                            Description = "We deliver the highest quality clothing for the lowest market price.",
                            NumberOfEmployees = 1568,
                            PhoneNumber = "214-858-4478",
                            State = "AZ",
                            StreetAddress = "618 Eastern St",
                            WebsiteUrl = "www.asos.com",
                            ZipCode = "88452"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
