// <auto-generated />
using System;
using Demo.Services.CompanyAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Services.CompanyAPI.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20230725045120_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Services.CompanyAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Demo.Services.CompanyAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61777b2c-964d-4ad7-974c-dc75037e4b89"),
                            CompanyId = new Guid("5108f4f8-2089-44d9-8ad1-06c3614f3cd5"),
                            Description = "Model's height: 188cm / 6' 2'. Model is wearing: Medium",
                            Name = "oversized T-shirt in beige ribbed velour",
                            Price = 32.0,
                            Style = 0
                        },
                        new
                        {
                            Id = new Guid("af9461b2-b795-4312-94e7-d770a353c961"),
                            CompanyId = new Guid("bb70a575-4973-4e63-bed4-7caae254364d"),
                            Description = "Machine wash according to instructions on care labels",
                            Name = "versized t-shirt in dark khaki with back fruit print",
                            Price = 26.100000000000001,
                            Style = 0
                        },
                        new
                        {
                            Id = new Guid("9135cb05-9652-4717-a4a6-81bf042fb86c"),
                            CompanyId = new Guid("a6b28790-528f-416d-9061-dee0fb935e22"),
                            Description = "Plain-woven fabric. Main: 100% Polyester.",
                            Name = "Nicce renee shorts in beige",
                            Price = 62.0,
                            Style = 3
                        },
                        new
                        {
                            Id = new Guid("1d176097-e2d3-4f5a-9989-5958d5361133"),
                            CompanyId = new Guid("5108f4f8-2089-44d9-8ad1-06c3614f3cd5"),
                            Description = "Satin-style fabric: glossy, drapey and silky-smooth. Main: 97% Cotton, 3% Elastane.",
                            Name = "satin slim shorts in black",
                            Price = 110.0,
                            Style = 3
                        },
                        new
                        {
                            Id = new Guid("99d45d6a-4bb5-46f8-8e8f-f139de57e61d"),
                            CompanyId = new Guid("bb70a575-4973-4e63-bed4-7caae254364d"),
                            Description = "Non-stretch denim: mid-blue wash. Main: 100% Cotton.",
                            Name = "oversized denim jacket in mid wash",
                            Price = 195.0,
                            Style = 4
                        },
                        new
                        {
                            Id = new Guid("9a637913-87c9-4741-b5f3-1b4ff7a98ad9"),
                            CompanyId = new Guid("a6b28790-528f-416d-9061-dee0fb935e22"),
                            Description = "Corduroy: ribbed, velvet-feel texture. Lining: 100% Polyester, Rib: 99% Polyester, 1% Elastane, Shell: 91% Polyester, 9% Nylon, Wadding: 100% Polyester.",
                            Name = "COLLUSION cord jacket in chocolate brown",
                            Price = 86.900000000000006,
                            Style = 4
                        });
                });

            modelBuilder.Entity("Demo.Services.CompanyAPI.Models.Product", b =>
                {
                    b.HasOne("Demo.Services.CompanyAPI.Models.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Demo.Services.CompanyAPI.Models.Company", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
