// <auto-generated />
using System;
using Demo.Services.AccountAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Services.AccountAPI.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20230915034646_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Services.AccountAPI.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("04bf4cb3-2fbf-421f-969b-4fbc4867cd28"),
                            Email = "kimavery@gmail.com",
                            FirstName = "Kimani",
                            FullAddress = "1212 N Vegas St, CityScape NV 54898",
                            LastName = "Avery"
                        },
                        new
                        {
                            Id = new Guid("51bef997-5840-44a0-9e97-c2bff5dade9a"),
                            Email = "tomf@outlook.com",
                            FirstName = "Tom",
                            FullAddress = "4859 Uptown Blvd, Downtowm TX 98922",
                            LastName = "Ford"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
